{% set version = "0.5-2" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bridgesampling
  version: {{ version|replace("-", "_") }}

source:
  fn: bridgesampling_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/bridgesampling_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/bridgesampling/bridgesampling_{{ version }}.tar.gz
  sha256: d9128e82ecd020eaf7115a77c510de7ea5a0025a2a240067b905618608e1b63b

build:
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-brobdingnag
    - r-matrix
    - r-coda
    - r-mvtnorm
    - r-scales
    - r-stringr

  run:
    - r-base
    - r-brobdingnag
    - r-matrix
    - r-coda
    - r-mvtnorm
    - r-scales
    - r-stringr

test:
  commands:
    - $R -e "library('bridgesampling')"  # [not win]
    - "\"%R%\" -e \"library('bridgesampling')\""  # [win]

about:
  home: https://github.com/quentingronau/bridgesampling
  license: GPL (>= 2)
  summary: Provides functions for estimating marginal likelihoods, Bayes factors, posterior model
    probabilities, and normalizing constants in general, via different versions of bridge
    sampling (Meng & Wong, 1996, <http://www3.stat.sinica.edu.tw/statistica/j6n4/j6n43/j6n43.htm>).
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
