appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: IgAiUm5be42fpzcIGwkdILVLHl0k9IblOV5tsxrZB982nIZ+Ey290C2WcpWEXgZx32pvvJZEssUgd4QFk1LGWfWQXGwP8g+K87Q0MNuTexwq0JMTjrZWq5dAt49i+P8YGZX8C+zJ60PUClmjYSIdEHExTPham/k+OG90oGrH331Do+ShYY/dW/RxsYGc/doEEfI/mXUiJ25KZT3Nf5dvuwzIbUIYaCh0Rtg9JJ5oIJXXl+8YqH8V1DY0UJg205t81vsGxMVZNWs24zzYasnPVZu2TvsAxtPRpysR9vL5NWYmJE/YIp5/0oTAfytPKQKh9oayvqwHX3npikLNkblW0mIlTsqqLnqsNz4qh15MYEnwm5rGm8+P+2PBl3EiISzQydNUjqJZMhwbKoPod9ckVmC9AugLSdz6lD0wmal1aS919RNUOziBYzCbr9pYp4OM9PN3jUDGvyuZC6re9nbz7jjspz3Ia57YLnYMrT/WzkhCOp5SpT/yhO4NYU6z8l9e0iAR8tfnTeud6v6WUIMelyZJYlcOeuRpNMR592RsTdP7frGmsr47ykxjXSZUVQUwl9UFoP8LBJcwG0Kgp1cZkH/Ie8rUIvTFha5xzBFxKxBsVg67uR4ci8vz07b/TJep9cCVddlf7MrvFvwHwpUynpqxNm6VWjgVjcFvJuItP/Y=}
