travis:
  secure:
    BINSTAR_TOKEN: eUG/I9m+vqyRulpH3NxiHBl6pywcWS6S/EP+sh4IwYdT9z9oQOEzoMHPuewU24azr2eToSkxBRyotCf3rCxXIGZfHw8vXmrVyfJ4KUMvTO61h+EFnWpkjqX+BV7f1/0Fwu9RWptoT8FPJe+RPxAa9UVm63xxWpiwffCIB4f02m2HgymfSwuuVrxLJ65/A4B4ji2i01OUmQom2Rn25bV6h20keQs2jEmJEFPGW+g0gtvQC5XcKFKbLtmQPDdQPIZf7jnGOK7FQNJ92y7Xl7y3O+66ss8kM3akO15mxIRFZ7eIG58uqGVJBtOwRIkXD5iLr//MhgdeQ8DzSWhd+WrEhixntabe6kPuoTdt6KcxMAOj9cH9M17amwJRh07laKA7fGtEv3v3ClBzZpnwZLovuRxxe0wEsihylUU7w5/eX+3DRHnsAfiQxzjfdtvbAOh6LcwDnKqKK7q7WPiR39m7PShNsu2xa5uFAzfLaovfip3oGz8134IxZkYVeUiUx+iMaUB1/7h5ibUyySmrp36mlLPFXDqQ3faz7eaiYkw1f+WYW7SqasRfjjpB6Gg/gvmTyqOpOE3eQCGwhzbTEcz+7QNbsuui1mkuisSoG9LYRXK07X82OPTse1VtEoq5dsYtuPwlYJYfmXwPLk+igF5AQFUQF4yE51EY9YaI7i5dzhA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
